### ISSUE TITLE
Opening a non running container from Home returns an error

### ISSUE THREAD

**Issue by Nyryus** [f4n0/Gordon#3]
**Describe the bug**

**To Reproduce**
1. Go to Home
2. Click on one of the Last Used Services that is not running 
3. Wait for timeout

**Expected behavior**

**Screenshots**
![image](https://github.com/f4n0/Gordon/assets/40896051/c2cd4de9-7b20-484a-a715-8300bb9cedcb)

**Product**
- [ ] Gordon WebApp (Version: 1.0.65.0)
- [ ] Gordon Powershell (Version: Boh)
- [ ] Bare.WebApi (Version: NaN)

**Additional Context**
The error is different from Docker Containers interface
![image](https://github.com/f4n0/Gordon/assets/40896051/bccc1ded-eba0-4df3-ba21-6353e6b8b4d5)

**Comment by f4n0** [comment]
done
